sd_model: models/Illustrious.safetensors
ollama_model: goekdenizguelmez/JOSIEFIED-Qwen3:8b-q6_k
ollama_vision_model: qwen2.5vl:7b
ollama_base_url: http://localhost:11434
gpu_backend: cuda
load_models_on_startup: true
cuda_settings:
  device: cuda:0
  dtype: float16
  enable_tf32: true
  memory_fraction: 0.95
generation_defaults:
  steps: 15
  guidance_scale: 7.5
  width: 512
  height: 512
batch_size: 1
conda_env: illustrious
gallery_dir: /tmp/illustrious_ai/gallery

# Memory Guardian Configuration
memory_guardian:
  enabled: true
  profile: balanced  # conservative, balanced, aggressive
  auto_model_switching: true
  auto_resolution_scaling: true
  auto_batch_adjustment: true
  enable_cpu_fallback: true
  log_memory_stats: true
  intervention_cooldown: 5.0  # seconds between interventions
  
  # Memory thresholds (as percentages)
  thresholds:
    low: 70      # Start monitoring closely
    medium: 85   # Begin preventive actions
    high: 95     # Aggressive memory management
    critical: 98 # Emergency intervention
  
  # Safety margins (in GB)
  safety_margins:
    generation_reserve: 2.0  # Reserve for image generation
    llm_reserve: 1.5         # Reserve for LLM operations
  
  # Monitoring intervals (in seconds)
  monitoring:
    normal_interval: 2.0      # Normal monitoring frequency
    aggressive_interval: 0.5  # When under memory pressure
