sd_model: models/Illustrious.safetensors
ollama_model: goekdenizguelmez/JOSIEFIED-Qwen3:8b-q6_k
ollama_vision_model: qwen2.5vl:7b
ollama_base_url: http://localhost:11434
gpu_backend: cuda
load_models_on_startup: true
cuda_settings:
  device: cuda:0
  dtype: float16
  enable_tf32: true
  memory_fraction: 0.95
generation_defaults:
  steps: 30
  guidance_scale: 7.5
  width: 1024
  height: 1024
  batch_size: 1
conda_env: illustrious
